const s = [
  "Sink",
  "Faucet",
  "Soap",
  "Handwash",
  "Towel",
  "Mirror",
  "Toilet",
  "Toilet Paper",
  "Shower",
  "Bathtub",
  "Shampoo",
  "Conditioner",
  "Body Wash",
  "Soap Dispenser",
  "Toothbrush",
  "Toothpaste",
  "Razor",
  "Shaving Cream",
  "Towel Rack",
  "Bath Mat",
  "Shower Curtain",
  "Toilet Brush",
  "Toilet Seat",
  "Flush Handle",
  "Bidet",
  "Tissues",
  "Trash Can",
  "Plunger",
  "Air Freshener",
  "Hairdryer",
  "Comb",
  "Brush",
  "Mouthwash",
  "Dental Floss",
  "Hand Towel",
  "Bath Towel",
  "Soap Dish",
  "Shower Head",
  "Drain",
  "Bathrobe",
  "Slippers",
  "Light Switch",
  "Exhaust Fan",
  "Cabinet",
  "Shelf",
  "Lotion",
  "Face Wash",
  "Mirror Cabinet",
  "Cotton Swabs",
  "Cotton Pads",
  "Razor Holder",
];
export default s;
