const s = [
  "Printer",
  "Desk",
  "Chair",
  "Monitor",
  "Mouse",
  "Keyboard",
  "Paper",
  "Stapler",
  "Pen",
  "Pencil",
  "Notebook",
  "Lamp",
  "Drawer",
  "Folder",
  "Filing Cabinet",
  "Computer",
  "Laptop",
  "Charger",
  "Whiteboard",
  "Marker",
  "Projector",
  "Screen",
  "Phone",
  "Headphones",
  "Desk Organizer",
  "Calendar",
  "Clock",
  "Tape",
  "Scissors",
  "Glue",
  "Paperclip",
  "Sticky Notes",
  "Highlighter",
  "Document",
  "Envelope",
  "Scanner",
  "Copier",
  "Router",
  "Ethernet Cable",
  "Mousepad",
  "Trash Bin",
  "Shredder",
  "Air Conditioner",
  "Vent",
  "Window",
  "Blinds",
  "Curtain",
  "Door",
  "Doorknob",
  "Key",
  "Badge",
  "ID Card",
  "Office Chair",
  "Meeting Room",
  "Conference Table",
  "Notepad",
  "Coffee Machine",
  "Mug",
  "Water Cooler",
  "Cabinet",
  "Shelf",
  "Bookcase",
  "Bulletin Board",
  "USB Drive",
  "Hard Drive",
  "Server",
  "Router",
  "Ethernet Port",
  "Power Strip",
  "Extension Cord",
  "Wall Socket",
  "Charger",
  "Keyboard Tray",
  "Wastebasket",
  "Carpet",
  "Ceiling",
  "Light Switch",
  "Electrical Outlet",
  "Speaker",
  "Microphone",
  "Ventilation",
  "Filing Tray",
  "Desk Lamp",
  "Binder",
  "Paper Tray",
  "Printer Paper",
  "Ink",
  "Toner",
  "Paper Cutter",
  "Label Maker",
  "Wall Clock",
  "Blueprint",
  "Paperweight",
];
export default s;
